# Generated by Django 5.0.10 on 2026-09-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
    ]
