# Generated by Django 5.0.10 on 2026-10-02 09:39

import core.orm.fields
import core.orm.fields.scalar
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', core.orm.fields.scalar.ULIDField(default=core.orm.fields.scalar.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=64, verbose_name='Label')),
                ('status', models.CharField(default='draft', max_length=16, verbose_name='Status')),
                ('label_upper', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper('label'), null=True, output_field=models.CharField(max_length=64), verbose_name='Label (upper)')),
                ('line_count', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.IntegerField(), stored=True, verbose_name='Line count')),
                ('total', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.DecimalField(decimal_places=2, max_digits=12), stored=True, verbose_name='Total')),
                ('total_of_amounts', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.DecimalField(decimal_places=2, max_digits=12), stored=True, verbose_name='Total of amounts')),
                ('tag_count', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.IntegerField(), stored=True, verbose_name='Tag count')),
                ('tag_popularity', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.IntegerField(), stored=True, verbose_name='Tag popularity')),
                ('tag_names', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.CharField(max_length=255), stored=True, verbose_name='Tag names')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('order_count', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.IntegerField(), stored=True, verbose_name='Order count')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit price')),
                ('amount', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), null=True, output_field=models.DecimalField(decimal_places=2, max_digits=12), verbose_name='Amount')),
                ('order_status', core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.CharField(max_length=16), stored=True, verbose_name='Order status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='computed_app.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='computed_app.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='orders', to='computed_app.tag', verbose_name='Tags'),
        ),
    ]
