# Generated by Django 5.0.10 on 2026-10-05 19:35

import core.orm.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computed_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='top_category',
            field=core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.CharField(max_length=64), stored=True, verbose_name='Top category'),
        ),
        migrations.AddField(
            model_name='order',
            name='top_category_ref',
            field=core.orm.fields.ComputedField(blank=True, editable=False, null=True, output_field=models.IntegerField(), stored=True, verbose_name='Top category (id)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='computed_app.category', verbose_name='Category'),
        ),
    ]
