# Generated by Django 5.0.10 on 2026-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code.', max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(check=models.Q(('code__regex', '^[A-Z]{2}$')), name='country_code_iso_alpha2', violation_error_message='The country code must be 2 uppercase letters (ISO 3166-1 alpha-2).'),
        ),
    ]
