# Generated by Django 5.0.8 on 2024-10-15 13:10

import base.files.storages
import core.orm.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', core.orm.fields.ULIDField(default=core.orm.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Path in the filestore', max_length=256, verbose_name='Name')),
                ('content', models.FileField(max_length=256, storage=base.files.storages.PublicMediaFileSystemStorage(), upload_to='website/%Y/%m')),
                ('checksum', models.CharField(help_text='SHA1 of the binary data of the file', max_length=128, verbose_name='Checksum')),
                ('mimetype', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mimetype')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
    ]
