# Generated by Django 5.0.10 on 2026-09-07 13:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='page_unique_slug',
        ),
        migrations.RemoveConstraint(
            model_name='widget',
            name='widget_unique_position',
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_path',
            field=models.CharField(db_index=True, editable=False, help_text='Use to fetch all menu tree at once.', max_length=256, verbose_name='Parent Path'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='param_limit_item',
            field=models.IntegerField(blank=True, help_text='Used to limit the number of item to display in the widget.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Max Item to Display'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('slug',), name='page_unique_slug', violation_error_message='A document with that slug already exists.'),
        ),
        migrations.AddConstraint(
            model_name='widget',
            constraint=models.UniqueConstraint(fields=('position',), name='widget_unique_position', violation_error_message='Another widget already occupies this position.'),
        ),
    ]
