# Generated by Django 5.0.10 on 2026-09-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_page_page_unique_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.AddField(
            model_name='website',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text='Page rendered at the root of the website.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='website.page', verbose_name='Homepage'),
        ),
    ]
