# Generated by Django 5.0.10 on 2026-09-10 19:39

import website.theme
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_widget_website_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=website.theme.get_layout_choices, default='full-width', help_text='Structure of the page body. Layout ids are a vocabulary shared by every theme; a theme that does not implement one falls back when the page renders, which is why switching theme cannot invalidate a page.', max_length=64, verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme',
            field=models.CharField(default='default', help_text='Identifier of the theme the website is rendered with. A theme is code, not a row: see `website.theme`. Only the selection is stored.', max_length=64, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_options',
            field=models.JSONField(blank=True, default=dict, help_text="Values for the options the selected theme declares in its `option_schema`. Holds the author's explicit overrides only: an option left unset falls back to the schema default when the page renders, so a theme adding an option needs no data migration.", verbose_name='Theme Options'),
        ),
    ]
