# Generated by Django 5.0.10 on 2026-09-11 14:38

import core.orm.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_page_layout_website_theme_website_theme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='side_bar_content',
            field=core.orm.fields.HtmlField(blank=True, null=True, verbose_name='Sidebar Content'),
        ),
    ]
