# Generated by Django 5.0.10 on 2026-09-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_website_side_bar_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='cover_media',
            field=models.ForeignKey(blank=True, help_text='Image a theme may show on the homepage. Whether it appears is up to the theme: a layout with nowhere to put one ignores it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.media', verbose_name='Cover Image'),
        ),
    ]
