"""
Django settings for totem project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import sys
from pathlib import Path

from core.utils.various import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('TOTEM_SECRET_KEY', default=False)
DEBUG = env('TOTEM_DEBUG', default=False, boolean=True)

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = env('TOTEM_CSRF_TRUSTED_ORIGINS').split(',')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "oauth2_provider",
    "django_celery_beat",
    "base",
    "oauth",
    "user",
    "website",
    "contact",
    # `core` must be last since it autodiscover `api` module
    # of each app, and generate schema on the fly (all models and
    # other auto loading stuff).
    "core",
]

# Test-only apps, exercising the framework layer of `core` with models of their
# own. Never installed outside the test runner, so their tables never exist in a
# real database; `TOTEM_TEST_APPS=true` installs them for `makemigrations`.
TESTING = sys.argv[1:2] == ["test"] or env("TOTEM_TEST_APPS", default=False, boolean=True)
if TESTING:
    # Before `core`, which must stay last.
    INSTALLED_APPS.insert(INSTALLED_APPS.index("core"), "core.tests.computed_app")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'totem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'environment': 'totem.jinja2.environment',
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'totem.wsgi.application'
ASGI_APPLICATION = 'totem.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_NAME"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = (('en-us', 'English'), ('fr', 'French'))

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/usr/src/static"
MEDIA_URL = "/media/"
MEDIA_ROOT = "/usr/src/media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth and Users
AUTH_USER_MODEL = "user.User"


# OAuth Toolkit

OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth.OAuthApp'
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth.AccessToken'
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'oauth.RefreshToken'
OAUTH2_PROVIDER_ID_TOKEN_MODEL = 'oauth.IDToken'
OAUTH2_PROVIDER_GRANT_MODEL = 'oauth.Grant'

OAUTH2_PROVIDER = {
    'SCOPES_BACKEND_CLASS': 'oauth.scopes.TotemScopes',
    'OAUTH2_VALIDATOR_CLASS': 'oauth.validators.OAuth2Validator',
    "OIDC_ENABLED": False, # for now ...
    "DEFAULT_SCOPES": [],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 60 * 10,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 60 * 60 * 5,  # 5 hours
}

# CORS Headers Settings

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True


# Logging
# Logs are the only trace of the background jobs (no Celery result backend):
# the worker logs each task received, succeeded (with its duration) or failed
# (with its traceback).

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(processName)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("TOTEM_LOG_LEVEL", default="INFO"),
    },
}


# Celery
# Redis is the broker; the schedules of the periodic tasks live in the
# database (`django_celery_beat`), editable from the admin.

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_TIMEZONE = TIME_ZONE
# No result backend: a task outcome is only logged.
CELERY_TASK_IGNORE_RESULT = True
# A task is acknowledged once done, so it is redelivered if the worker dies
# while running it. Tasks must therefore be idempotent.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Redis redelivers an unacknowledged task after this delay: it must exceed the
# longest task duration, or the task runs twice.
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 60 * 60}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Keep the `LOGGING` above instead of Celery's own root logger setup.
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
