# Generated by Django 5.0.10 on 2026-08-26 08:59

import core.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('color', models.PositiveSmallIntegerField(default=0, help_text='Index in the front-end color palette.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Contact Tag',
                'verbose_name_plural': 'Contact Tags',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('number', models.CharField(blank=True, help_text='Street number, not necessarily numeric (12A, 3 bis, ...).', max_length=32, null=True, verbose_name='Number')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('zip', models.CharField(blank=True, max_length=32, null=True, verbose_name='Zip')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='Mobile')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_contact_tag_name', violation_error_message='A tag with that name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.CheckConstraint(check=models.Q(('color__gte', 0), ('color__lte', 15)), name='contact_tag_color_range', violation_error_message='The color must be between 0 and 15.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contact.contacttag'),
        ),
    ]
